### PR TITLE
remove persistent buffers

### PR DESCRIPTION
**Pull request by rmrao**

### CODE REVIEW

**Comment by rmrao** [comment]
Buffers shouldn't be persistent

**Comment by nikita-smetanin** [comment]
True, I thought we already fixed this :)

**Review by nikita-smetanin — APPROVED** [review]

**Comment by ebetica** [comment]
I don't understand, the fix is literally right here https://github.com/ebetica/openfold/commit/1b5afb6b3d433ea550fa5a4900313f8a61c33298

**Comment by rmrao** [comment]
Ok I'm so confused I think it wasn't in main, but you're not on main, but I checked the file change and it says that all the `persistent=True` lines are new even though they're clearly in the file...

Whatever, I'll just close this - sorry!

**Pull request closed without merging**
